### PR TITLE
Add vuln

### PR DESCRIPTION
**Pull request by zuesdevil**
Add vuln of ASR

### CODE REVIEW

**Review by pr0b3r7 — CHANGES_REQUESTED** [review]
@zuesdevil -- please document the vulnerability introduced by this change (ASR)

**Comment by zuesdevil** [comment]
This vulnerability is set up to enhance the defense evasion section, defense evasion can make the lab closer to the real world. the full name of ASR is Attack surface reduction, which is configured in windows defender and Microsoft's EDR(Microsoft Defender for Endpoint). I have only one rule turned on in my policy. The rule that I commented out, although it can make a lot of operations less easy, I think it could be turned on as well.

**Comment by pr0b3r7** [comment]
> This vulnerability is set up to enhance the defense evasion section, defense evasion can make the lab closer to the real world. the full name of ASR is Attack surface reduction, which is configured in windows defender and Microsoft's EDR(Microsoft Defender for Endpoint). I have only one rule turned on in my policy. The rule that I commented out, although it can make a lot of operations less easy, I think it could be turned on as well.

Thank you for replying with this detail. I recommend adding more detail as to what does this specific ASR rule do. 

@Mayfly277 , unless you consider the above enough 'documentation' and/or want to update your walkthrough of the lab with this (I understand the ASR rule ID is in the code/changelog) I would expect to have details (at least in a comment in the changed file as to what does the ASR rule match). 

Cheers and thank you for contributing to this awesome project!

**Comment by zuesdevil** [comment]
Okay, I don't have enough time to write walkthroughs. i can write about the idea of bypassing ASR in the comments. bypassing ASR rules ASR rules use hard-coding, so we can bypass them directly by using file exclusions!
ASR rule discovery way 1: we can use win10-asr-get.ps1 (https://raw.githubusercontent.com/directorcia/Office365/master/win10-asr-get.ps1) to discover the open item.
Way 2: we can dump vdm file and parse it via vdm_lua_extract.py (https://gist.github.com/HackingLZ/65f289b8b0b9c8c3a675aa26c06dfe09). After parsing the file we can see GetRuleInfo to see the information and GetPathExclusions to see the hardcoded file path.

In this config, the first rule I have enabled Block credential stealing from the Windows local security authority subsystem policy (GUID:9e6c4e1f-7d60-472f-ba1a-a39ef669e4b2,  ), in addition to bypassing it with file exclusions, we can bypass it by injecting it into an existing exclusion process. another one rule I commented out is Block process creations originating from PSExec and WMI commands (GUID:d1e49aac-8f56-4280-b9ba-993a6d77406c). by the way, I think we can still open it because the way to bypass the rules is still to utilize the file exclusion feature.

**Comment by pr0b3r7** [comment]
> I would expect to have details (at least in a comment in the changed file as to what does the ASR rule match).

@zuesdevil - I'm not suggesting or asking you to write a walk-through, please check my quoted reply above. Adding a comment in the files changed for the PR is sufficient IMHO. The idea is that someone other than you that is learning/studying ASR can see the answer if so they choose. The project is for the benefit of the community at large/all levels of knowledge. Not for an individual. You know what you put there but some others might not. It's all.

**Comment by zuesdevil** [comment]
Okay, i'll close this PR and resubmit it. thank you for your advice.



---Original---
From: ***@***.***&gt;
Date: Tue, Nov 21, 2023 11:24 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Orange-Cyberdefense/GOAD] Add vuln (PR #124)




  
I would expect to have details (at least in a comment in the changed file as to what does the ASR rule match).
  
@zuesdevil - I'm not suggesting or asking you to write a walk-through, please check my quoted reply above. Adding a comment in the files changed for the PR is sufficient IMHO. The idea is that someone other than you that is learning/studying ASR can see the answer if so they choose. The project is for the benefit of the community at large/all levels of knowledge. Not for an individual. You know what you put there but some others might not. It's all.

**Pull request closed without merging**
