### PR TITLE
Proxmox v8.x support

### PR DESCRIPTION
**Pull request by aancw**
When using the Telmate/Proxmox v2.9.14, it will not working for proxmox v8.x and showing error like this

```
╷
│ Error: Plugin did not respond
│
│   with proxmox_vm_qemu.srv02,
│   on goad.tf line 85, in resource "proxmox_vm_qemu" "srv02":
│   85: resource "proxmox_vm_qemu" "srv02" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with proxmox_vm_qemu.srv03,
│   on goad.tf line 112, in resource "proxmox_vm_qemu" "srv03":
│  112: resource "proxmox_vm_qemu" "srv03" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 68 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc0005a4718, 0xc9d509?)
	github.com/Telmate/proxmox-api-go@v0.0.0-20230319185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0000dcf80, {0xb66f60?, 0xc000478000})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:972 +0x2c4d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xdd7840?, {0xdd7840?, 0xc0006173b0?}, 0xd?, {0xb66f60?, 0xc000478000?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002ca7e0, {0xdd7840, 0xc0006173b0}, 0xc000453040, 0xc0000dce00, {0xb66f60, 0xc000478000})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000354b70, {0xdd7840?, 0xc000617290?}, 0xc00022e550)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002303c0, {0xdd7840?, 0xc000616a80?}, 0xc00027e070)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc6bc20?, 0xc0002303c0}, {0xdd7840, 0xc000616a80}, 0xc00027e000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000370000, {0xddb420, 0xc0000e8ea0}, 0xc000545440, 0xc00036ed20, 0x128f7a0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc000370000, {0xddb420, 0xc0000e8ea0}, 0xc000545440, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!
```

Here is the discussion about this issue https://github.com/Telmate/terraform-provider-proxmox/issues/863 . As far as I understand, the Telmate repo already patched it but in rc1 release tag. So I've updated the script to use 

```
    proxmox = {
      source = "Telmate/proxmox"
      version = "3.0.1-rc1"
    }
```

After changing the script, it work

```
# terraform apply "goad.plan"
proxmox_vm_qemu.DC03: Destroying... 
proxmox_vm_qemu.srv02: Destroying... 
proxmox_vm_qemu.dc02: Destroying...
proxmox_vm_qemu.srv03: Creating...
proxmox_vm_qemu.dc01: Creating...
proxmox_vm_qemu.DC03: Destruction complete after 2s
proxmox_vm_qemu.dc02: Destruction complete after 2s
proxmox_vm_qemu.srv02: Destruction complete after 2s
proxmox_vm_qemu.DC03: Creating...
proxmox_vm_qemu.dc02: Creating...
proxmox_vm_qemu.srv02: Creating...
proxmox_vm_qemu.dc01: Still creating... [10s elapsed]
proxmox_vm_qemu.dc02: Still creating... [10s elapsed]
proxmox_vm_qemu.srv02: Still creating... [10s elapsed]
proxmox_vm_qemu.dc02: Still creating... [20s elapsed]
proxmox_vm_qemu.srv02: Still creating... [20s elapsed]
proxmox_vm_qemu.dc02: Still creating... [30s elapsed]
proxmox_vm_qemu.srv02: Still creating... [30s elapsed]
```

### CODE REVIEW

**Comment by aancw** [comment]
Stuck in creating disk https://github.com/Telmate/terraform-provider-proxmox/issues/959#issuecomment-1986833495. On my work to use `master` branch that fix the issue but need to modify the goad.tf for disk section.

**Comment by aancw** [comment]
Success deploying with proxmox v8, but without pool name. Because when using pool variable it will give an error and fail to deploy.

```
2024-03-19T16:43:56.952Z [ERROR] provider.terraform-provider-proxmox_v3.0.1-rc1: Response contains error diagnostic: tf_proto_version=5.4 tf_rpc=ApplyResourceChange diagnostic_severity=ERROR diagnostic_summary="error updating VM: 400 Parameter verification failed., error status: {\"data\":null,\"errors\":{\"pool\":\"property is not defined in schema and the schema does not allow additional properties\"}} (params: map[agent:1 bios:seabios boot:order=sata0;ide3 cores:2 cpu:host delete:ide0,sata3,sata4,sata5 description:DC02 - windows server 2019 - 192.168.10.11 hotplug:network,disk,usb ide2:none,media=cdrom ide3:local-lvm:cloudinit,format=raw ipconfig0:ip=192.168.10.11/24,gw=192.168.10.1 kvm:true memory:3096 name:GOAD-DC02 nameserver:192.168.10.1 net0:e1000=A6:9A:3F:F0:3E:01,bridge=vmbr3,tag=10 numa:false onboot:false ostype:win10 pool:GOAD sata0:local-lvm:vm-107-disk-0,replicate=0 scsihw:lsi sockets:1 tablet:true vmid:107])" tf_req_id=f4e39815-c8a9-0182-6fdc-628d5170e417 diagnostic_detail="" @module=sdk.proto tf_provider_addr=registry.terraform.io/telmate/proxmox @caller=github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov5/internal/diag/diagnostics.go:62 tf_resource_type=proxmox_vm_qemu timestamp=2024-03-19T16:43:56.952Z
```

Here is the proof
image

**Comment by Mayfly277** [comment]
hello, i am sorry but thegameprofi/proxmox is archived : https://github.com/TheGameProfi/terraform-provider-proxmox 
So i will prefer to change to bgp/proxmox like suggested in this issue : 
https://github.com/Orange-Cyberdefense/GOAD/pull/190
this seems a way more active :)

thx for your help about issues in proxmox 8 anyway

**Comment by aancw** [comment]
@Mayfly277 I'm not using  https://github.com/TheGameProfi/terraform-provider-proxmox, for this support i'm using https://github.com/Telmate/terraform-provider-proxmox

**Comment by Mayfly277** [comment]
oh my bad ! x)

**Comment by Mayfly277** [comment]
sorry finally i have done a complete refactoring of proxmox terraform receipe and passed all to bgp/proxmox.
i close this pr.

**Pull request closed without merging**
