### PR TITLE
Adding Vagrant installation step and other change about installation

### PR DESCRIPTION
**Pull request by V0lk3n**
Line 30-34 :

Add installation step for vagrant on Linux (Tested on Ubuntu 22.04), to avoid a WinRM Error from vagrant, see related issue : https://github.com/hashicorp/vagrant/issues/12807

Line 88-92 :

Move the git clone step to line 40-43, to better understand the "cd ansible" at the ansible installation step and change this with a "pwd" command.

### CODE REVIEW

**Comment by V0lk3n** [comment]
The vagrant installation step should fix this issue too https://github.com/Orange-Cyberdefense/GOAD/issues/11 

But this need to be confirmed, i got the same error, but i can't remember which of my step fixed it

**Comment by V0lk3n** [comment]
I've added a commit to fix the file name from vulns.yml to vulnerability.yml

**Comment by V0lk3n** [comment]
I've added commit to install chocolatey, as it's needed for running elk.yml using ansible-playbook.

**Comment by V0lk3n** [comment]
Hum?

**Comment by V0lk3n** [comment]
@Mayfly277 any update?

**Comment by Mayfly277** [comment]
thx for the pull request, i will test it next week ;)

**Comment by V0lk3n** [comment]
Thanks :)

**Pull request merged**
