### PR TITLE
Add ESXi support to GOAD scenario using esxi Vagrant plugin

### PR DESCRIPTION
**Pull request by kripskroll**
First of all : Many thanks to this AWESOME repo.

This Vagrantfile is giving a way to integrate with ESXi using Vagrant Plugin from : https://github.com/josenk/vagrant-vmware-esxi
I know that is a dead architecture, but I have one up and running and it helps me a lot to use it. So I thought it should help others.
There is no modification in the `inventory` file. Just copied in folder for consistency

These lines need to be customised to match your lab environment: 

```
esxi.esxi_hostname         = '10.10.10.10'
esxi.esxi_username         = 'USERNAME'
esxi.esxi_password         = 'PASSWORD'
esxi.esxi_virtual_network  = ["LAN Mgt 10.10.10", "LAN LAB"]
esxi.esxi_disk_store.      = 'ESXI-DATASTORE'
```

It must be launch from repository `ad/GOAD/providers/esxi/` using `vagrant up` 

TODO:

- Better manage user environment variables
- Add esxi provider in goad.sh script
- Anything you want :)

I hope it should help and thanks again

### CODE REVIEW

**Comment by Mayfly277** [comment]
thx, but also covered by https://github.com/Orange-Cyberdefense/GOAD/pull/210

**Comment by kripskroll** [comment]
Hi, 
I highly suspect that Viris took my work and "just" sanitized it, improved it.
I created the merge request March 27th and all by sudden he created his one April 2nd.
I'm not someone running after reconnaissance but this is the 1st time it happens to me and that is frustrating.
Now his job is really nice and he has improved the work the right way. But doing and improving are 2 different things.

Thanks

**Comment by viris** [comment]
@kripskroll 

Well if you want proof I was working on this thing way before, here you go:
https://discord.com/channels/1024782286274699314/1024782286274699317/1059778814252687411 - Told that I was trying to get this thing to work on GOAD community Discord at date 2023-01-03
https://discord.com/channels/1024782286274699314/1024782286274699317/1126417614655213619 - Original Vagrantfile (sha256sum of `9b843ef4b3d213942a3fa6122b1d67a9fe941ffc4573a79014b224cab8d0441f`) I shared on GOAD community discord at date 2023-07-06

image

image

There was an additional incentive to make this a breeze based on post https://z-sec.co/guide-to-install-game-of-active-directory-goad-on-vmwareesxi that was also shared on that Discord on 2024-03-20 and additionally new labs were an inspiration since we wanted to test this on ESXi so the timing was similar because of that and expiration of our previous lab setup. But I did see your pull request but since it was not even half done and no activity and we wanted things to fully work I decided to publish a new one.

But yeah It wasn't my intention to deduct from the work you did.

**Comment by kripskroll** [comment]
Thanks for your explanations @viris and sorry to have been suspicious.
And yes my work was half done and again your work is massively nice :)

**Pull request closed without merging**
